trainer:
  DATA_PATH: "data/" #data location
  SAVE_BEST_MODEL: True
  MODEL_SAVE_FOLDER: "models" 
  HIDDEN_CHANNELS: 256
  BATCH_SIZE: 32
  EPOCHS: 100
  SEED: 42
  CLEAN_DATA: True
  MIN_AFFINITY: 5
  MAX_AFFINITY: 11
  MEAN_LOWER_BOUND: 6.5
  MEAN_UPPER_BOUND: 7.5
  LOW_BOUND: 6
  HIGH_BOUND: 8
  GNN_MODEL: "GAT" # "GC_GNN" "GCN" "GAT" "GIN" "GINE" "GraphSAGE"
  EDGE_WEIGHT: True
  SCALING: True
  SEED: 42
  HIDDEN_CHANNELS: 256
  EPOCHS: 100
  LEARNING_RATE: 1e-3
  WEIGHT_DECAY: 5e-4
  NODE_FEATURES: True

explainer:
  DATA_PATH: "data/" #data location
  SAVE_FOLDER: 'results/additional_experiments/pgexplainer_explanations/' #folder where explanations will be saved
  MODEL_PATH: 'models/pretrained_models/model_GraphSAGE_best_71.ckpt' #model to use for the explanation phase
  GNN_MODEL: "GraphSAGE" # "GC_GNN" "GCN" "GAT" "GIN" "GINE" "GraphSAGE"
  SAMPLES_TO_EXPLAIN: 20 #number of test samples to explain
  AFFINITY_SET: "high" #affinity set for which to perform the explanations (low, medium, high)
  HIDDEN_CHANNELS: 256
  BATCH_SIZE: 32
  EPOCHS: 100
  SEED: 42
  CLEAN_DATA: True
  MIN_AFFINITY: 5
  MAX_AFFINITY: 11
  MEAN_LOWER_BOUND: 6.5
  MEAN_UPPER_BOUND: 7.5
  LOW_BOUND: 6
  HIGH_BOUND: 8
  EDGE_WEIGHT: True #NOTE: If set to True, this will be ignored for GraphSAGE and GIN since they do not support edge weights
  SCALING: True
  SEED: 42
  HIDDEN_CHANNELS: 256
  EPOCHS: 100
  LEARNING_RATE: 1e-3
  WEIGHT_DECAY: 5e-4
  NODE_FEATURES: True

top_k_computation:
  DATA_PATH: "data/" #data location
  PLOT: True #if to save top_k graph images
  EXPLANATIONS_FOLDER: "results/additional_experiments/pgexplainer_explanations/GraphSAGE/" #folder where the explanations computed with explainer_script.py are
  TOP_K_VALUES: [5,10,15,20,25] #values for the top-k edges computation

statistics:
  DATA_PATH: "data/" #data location
  EXPLANATIONS_FOLDER: "results/explanations/GC_GNN/" 
  TOP_K_VALUES: [25] #values for the top-k edges computation
  MIN_AFFINITY: 5
  MAX_AFFINITY: 11
  MEAN_LOWER_BOUND: 6.5
  MEAN_UPPER_BOUND: 7.5
  LOW_BOUND: 6
  HIGH_BOUND: 8
  CLEAN_DATA: True


affinity_shifting:
  DATA_PATH: "data/" #data location
  MODEL_PATH: 'models/pretrained_models/model_GAT_best_98.ckpt' #model to use
  GNN_MODEL: "GAT" # "GC_GNN" "GCN" "GAT" "GIN" "GINE" "GraphSAGE"
  HIDDEN_CHANNELS: 256
  BATCH_SIZE: 32
  EPOCHS: 100
  SEED: 42
  CLEAN_DATA: True
  MIN_AFFINITY: 5
  MAX_AFFINITY: 11
  MEAN_LOWER_BOUND: 6.5
  MEAN_UPPER_BOUND: 7.5
  LOW_BOUND: 6
  HIGH_BOUND: 8
  EDGE_WEIGHT: True
  SCALING: True
  SEED: 42
  HIDDEN_CHANNELS: 256
  EPOCHS: 100
  LEARNING_RATE: 1e-3
  WEIGHT_DECAY: 5e-4
  NODE_FEATURES: True
  AFFINITY_SHIFT: 0.5  